name: zeronet
description: ZeroNet on Nostr
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  plugin_interface:
    path: ../../packages/plugin_interface
  nostr_wrapper:
    path: ../../packages/nostr
  wizard:
    path: ../../packages/wizard
  flutter_bloc:
  webview_flutter: ^4.13.1
  path_provider: ^2.1.0
  path: ^1.9.0
  file_picker: ^9.0.0
  crypto: ^3.0.6
  mime: ^2.0.0
  flutter_webrtc: ^0.12.12
  namecoin:
    git:
      url: https://github.com/Cyrix126/namecoin_dart
  electrum_adapter:
    git:
      url: https://github.com/cypherstack/electrum_adapter
      ref: 0de864a35c71fce3a07e6a53b623619b32394b8d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
