name: nostr_wrapper
description: Nostr abstraction layer wrapping dart-nostr
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  nostr:
    git:
      url: https://github.com/ethicnology/dart-nostr.git
      ref: develop
