name: dispute
description: A cross-platform Nostr client
publish_to: none
version: 2.0.0+1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  plugin_interface:
    path: ../../packages/plugin_interface
  nostr_wrapper:
    path: ../../packages/nostr
  flutter_bloc:
  web_socket: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
